# Generated by Django 4.1 on 2024-05-18 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_venda_itemvenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Total'),
        ),
    ]
