# Generated by Django 4.1 on 2024-05-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_venda_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemvenda',
            name='preco',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=8, verbose_name='Preço'),
        ),
    ]
